class ExperimentStore(Protocol):
    def create_run(...): ...
    def finish_run(...): ...
    def record_execution(...): ...
    def record_attempt(...): ...
    def record_score(...): ...
    def record_review(...): ...
    def append_event(...): ...
    def promote_regression(...): ...
    def get_run(...): ...
    def compare_runs(...): ...
